version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    stdin_open: true
